version: '3.8'
services:
  react-app:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - api-server
  api-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      PGHOST: db
      PGUSER: postgres
      PGDATABASE: raid_challenge_db
      PGPASSWORD: raid_challenge
      PGPORT: 5432
    ports:
      - 5000:5000
    depends_on:
      - db
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=raid_challenge
      - POSTGRES_DB=raid_challenge_db
    ports:
      - 5432:5432
    volumes:
      - ./server/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:

